fbfo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]

main/urls.py
from django.conf.urls import url
from . import views


app_name = 'main'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^home/$', views.home, name="home"),
    url(r'^api/form/edit/$', views.edit, name="edit"),
    url(r'^api/form/save/$', views.form_save, name="form_save"),
    url(r'^api/shortQues/save/$', views.short_ques_save, name="shortQuesSave"),
    url(r'^api/multipleQues/save/$', views.multiple__ques_save, name="multipleQuesSave"),
    url(r'^api/response/(?P<form_id>[0-9]+)/$', views.response, name="response"),
    url(r'^api/response/save/$', views.response_save, name="saveResponses"),
    url(r'^api/result/(?P<form_id>[0-9]+)/$', views.result, name="result"),
    url(r'^api/response/detail/(?P<response_id>[0-9]+)/$', views.response_detail,
        name="responseDetail"),
]

main/models.py
from __future__ import unicode_literals
from django.db import models


class Form(models.Model):
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=128)

    def __str__(self):
        return self.title


class ShortQuestion(models.Model):
    short_question_text = models.CharField(max_length=80)
    form = models.ForeignKey(Form, on_delete=models.CASCADE)

    def __str__(self):
        return self.short_question_text


class MultipleChoiceQuestion(models.Model):
    mc_question_text = models.CharField(max_length=80)
    form = models.ForeignKey(Form, on_delete=models.CASCADE)
    other = models.BooleanField(default=True)

    def __str__(self):
        return self.mc_question_text


class MultipleChoices(models.Model):
    choice_text = models.CharField(max_length=30)
    mc_question = models.ForeignKey(MultipleChoiceQuestion, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text


class Response(models.Model):
    form = models.ForeignKey(Form, on_delete=models.CASCADE)

    def __str__(self):
        return 'Resp: {}'.format(self.form.title)


class ShortResponse(models.Model):
    short_response_text = models.CharField(max_length=128)
    response = models.ForeignKey(Response, on_delete=models.CASCADE)
    short_question = models.ForeignKey(ShortQuestion, on_delete=models.CASCADE)

    def __str__(self):
        return self.short_response_text


class MultipleChoiceResponse(models.Model):
    response = models.ForeignKey(Response, on_delete=models.CASCADE)
    mc_question = models.ForeignKey(MultipleChoiceQuestion, on_delete=models.CASCADE)
    choices = models.ForeignKey(MultipleChoices, on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return '{}: {}'.format(self.accepted, self.choices.choice_text)


class MultipleChoiceOtherResponse(models.Model):
    other_response = models.CharField(max_length=30)
    response = models.ForeignKey(Response, on_delete=models.CASCADE)
    mc_question = models.ForeignKey(MultipleChoiceQuestion, on_delete=models.CASCADE)

    def __str__(self):
        return self.other_response

main/forms.py
from django import forms
from .models import *
import json


class AppForm(forms.ModelForm):
    class Meta:
        model = Form
        fields = ['title', 'description']


class ShortQuestionForm(forms.ModelForm):
    form = forms.ModelChoiceField(queryset=Form.objects.all())

    class Meta:
        model = ShortQuestion
        fields = ['short_question_text', 'form']


class MultipleQuestionForm(forms.Form):
    form = forms.ModelChoiceField(queryset=Form.objects.all())
    multiple_choice_question_text = forms.CharField(max_length=1024)
    options = forms.CharField(max_length=4096)

    def clean_options(self):
        options_json = self.cleaned_data['options']
        try:
            json_data = json.loads(options_json)  # loads string as json
        except:
            raise forms.ValidationError("Invalid data in options")
            # if json data not valid:
            # raise forms.ValidationError("Invalid data in jsonfield")
        return json_data

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from .forms import *
import json
from django.shortcuts import get_object_or_404


def index(request):
    return render(request, 'main/index.html')


def home(request):
    form_list = Form.objects.all()
    context = {
        'form_list': form_list,
    }
    return render(request, 'main/home.html', context)


def edit(request):
    return render(request, 'main/edit.html')


def form_save(request):
    if request.method == "POST":
        form = AppForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            f = Form()
            f.title = title
            f.description = description
            f.save()
            data = {
                'id': f.id,
                'title': f.title,
                'description': f.description
            }
            return HttpResponse(json.dumps(data), content_type='application/json', status=201)
    else:
        return HttpResponse(status=405)


def short_ques_save(request):
    if request.method == "POST":
        sq_form = ShortQuestionForm(request.POST)
        if sq_form.is_valid():
            form_object = sq_form.cleaned_data['form']
            short_question_text = sq_form.cleaned_data['short_question_text']
            sq = ShortQuestion()
            sq.form = form_object
            sq.short_question_text = short_question_text
            sq.save()
            data = {
                'id': sq.id,
                'short_question_text': sq.short_question_text,
            }
            return HttpResponse(json.dumps(data), content_type='application/json', status=201)
    else:
        return HttpResponse(status=405)


def multiple__ques_save(request):
    if request.method == "POST":
        mcq_form = MultipleQuestionForm(request.POST)
        if mcq_form.is_valid():
            form_object = mcq_form.cleaned_data['form']
            multiple_question_text = mcq_form.cleaned_data['multiple_choice_question_text']
            mcq = MultipleChoiceQuestion()
            mcq.form = form_object
            mcq.mc_question_text = multiple_question_text
            mcq.save()
            # import ipdb;ipdb.set_trace()
            for opt in mcq_form.cleaned_data['options']:
                choice = MultipleChoices()
                choice.choice_text = opt
                choice.mc_question = mcq
                choice.save()
            data = {
                'id': mcq.id,
                'mc_question_text': mcq.mc_question_text,
                'choices': [{
                    'id': choice.id,
                    'choice_text': choice.choice_text
                } for choice in MultipleChoices.objects.filter(mc_question=mcq)]

            }
            return HttpResponse(json.dumps(data), content_type='application/json', status=201)
    else:
        return HttpResponse(status=405)


def response(request, form_id):
    form = Form.objects.get(pk=form_id)
    sq_list = ShortQuestion.objects.filter(form=form)
    mcq_list = MultipleChoiceQuestion.objects.filter(form=form)
    context = {
        'form': form,
        'sq_list': sq_list,
        'mcq_list': [{
            'mcq': mcq,
            'choices': MultipleChoices.objects.filter(mc_question=mcq)
        } for mcq in mcq_list],
    }
    return render(request, 'main/response.html', context)


def response_save(request):
    if request.method == "POST":
        form_id = request.POST.get('form')
        form_object = Form.objects.get(id=form_id)
        resp = Response()
        resp.form = form_object
        resp.save()
        short_response_list = json.loads(request.POST.get('shortResponses'))
        for sr in short_response_list:
            short_response = ShortResponse()
            short_response.short_question = ShortQuestion.objects.get(id=sr['questionId'])
            short_response.short_response_text = sr['textResponse']
            short_response.response = resp
            short_response.save()
        multiple_choice_response_list = json.loads(request.POST.get('multipleChoiceResponses'))
        for mcqr in multiple_choice_response_list:
            for choice in mcqr['choices']:
                multiple_choice_response = MultipleChoiceResponse()
                multiple_choice_response.response = resp
                multiple_choice_response.mc_question = MultipleChoiceQuestion.objects.get(id=mcqr['questionId'])
                multiple_choice_response.choices = MultipleChoices.objects.get(id=choice['choiceId'])
                multiple_choice_response.accepted = choice['checked']
                multiple_choice_response.save()

        data = {
            'response': resp.id,
            'shortResponses': [{
                'id': shortResponse.id,
                'short_response_text': shortResponse.short_response_text
            } for shortResponse in ShortResponse.objects.filter(response=resp)],
            'multipleChoiceResponses': [{
                'id': multipleChoiceResponse.id,
                'accepted': multipleChoiceResponse.accepted
            } for multipleChoiceResponse in MultipleChoiceResponse.objects.filter(response=resp)]
        }
        return HttpResponse(json.dumps(data), content_type='application/json', status=201)
    else:
        return HttpResponse(status=405)


def result(request, form_id):
    form = Form.objects.get(pk=form_id)
    sq_list = ShortQuestion.objects.filter(form=form)
    responses = Response.objects.filter(form=form)
    count = responses.count()
    context = {
        'form': form,
        'sq_list': sq_list,
        'responses': responses,
        'count': count,
    }
    return render(request, 'main/response_list.html', context)


def response_detail(request, response_id):
    response = Response.objects.get(id=response_id)
    short_responses = ShortResponse.objects.filter(response=response)
    context = {
        'short_responses': short_responses,
        'form': response.form,
    }
    return render(request, 'main/response_detail.html', context)

main/templates/main/edit.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <div class="container">
        <h4 class="page-header">Form<span class="pull-right" id="responseUrl"></span><br><span class="pull-right" id="resultsUrl"></span></h4>
        <form class="form" id="appForm">
            {% csrf_token %}
            <input type="text" class="form-control" id="title" name="title" placeholder="Title"><br>
            <input type="text" class="form-control" id="desc" name="description" placeholder="Description"><br>
            <button id="formSave" type="submit" class="btn btn-default">Save</button>
        </form><br>
        <div id="questions_holder"></div>
        <button id="add_question_button" class="btn btn-default" type="button">Add Questions</button>
    </div>

<script type="text/html" id="general_question_template">
    <div data-id="general_question_cid">
        Question Type<br/>
        <select name="question-type" class="question_type_select">
            <option value="SQ">Short Question</option>
            <option value="MCQ">Multiple Choice Question</option>
        </select>
        <div class="actual_question_holder"></div>
    </div>
</script>

<script type="text/html" id="short_question_template">
    <form class="form">
        {% csrf_token %}
        <input type="text" class="form-control" id="shortQues" name="shortQues" placeholder="Short Question">
        <br><button id="shortQuesSaveBtn" type="submit" class="btn btn-default">Submit</button>
    </form><br>
</script>

<script type="text/html" id="multiple_choice_question_template">
    <form class="form">
        {% csrf_token %}
        <input type="text" class="form-control" id="multipleChoiceQues" name="multipleChoiceQues" placeholder="Multiple Choice Question">
        <div id="choices_holder"></div>
        <button id="addChoiceBtn" type="button" class="btn btn-default">Add Option</button>
        <br><button id="multipleChoiceQuesSaveBtn" type="submit" class="btn btn-default">Submit</button>
    </form><br>
</script>

<script type="text/html" id="choice_checkbox_template">
    <input type="text" data-id="option_ccid" class="form-control" name="multipleChoiceQues" placeholder="Option">
</script>

<script src="{% static 'main/js/jquery-3.1.1.js' %}"></script>
<script src="{% static 'main/js/jquery.loadTemplate.min.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
<script src="{% static 'main/js/app.js' %}"></script>
</body>
</html>

main/templates/main/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">FBFO</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Login</a></li>
            <li><a href="#">Logout</a></li>
            </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid" id="start-form">
        <h4 class="text-center">Start a new form</h4>
        <a href="{% url 'main:edit' %}">
            <div class="formBox text-center">
                Add
            </div>
        </a>
    </div>
    <div class="container-fluid" id="recent-forms">
        {% for form in form_list %}
            <div class="col-md-3">
                <a href="{% url 'main:result' form.id %}">
                    <div class="formBox text-center">
                        {{ form.title }}
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>

<script src="{% static 'main/js/jquery-3.1.1.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
</body>
</html>

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <style>
        html {
            background: url("{% static 'main/images/form.png' %}") no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
    </style>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">FBFO</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Login</a></li>
            <li><a href="#">Logout</a></li>
            </ul>
        </div>
      </div>
    </nav>
    <div class="container">
        <a href="{% url 'main:home' %}" class="btn btn-info">Go to Forms</a>
    </div>
<script src="{% static 'main/js/jquery-3.1.1.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
</body>
</html>

main/templates/main/response.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Response</title>
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <div class="container" id="response-container">
        <h3 class="page-header" form-id="{{ form.id }}" id="mainForm">{{ form.title }}</h3>
    <div id="shortResponses">
        {% for sq in sq_list %}
            <h4>{{ sq.short_question_text }}</h4>
            <form class="form">
{#                {% csrf_token %}#}
                <input type="text" class="form-control" id="shortResponse{{ sq.id }}" question-id="{{ sq.id }}" name="shortResponse{{ sq.id }}">
            </form>
        {% endfor %}
    </div>
    <div id="multipleChoiceResponses">
        {% for mcq in mcq_list %}
            <h4>{{ mcq.mcq.mc_question_text }}</h4>
            <form class="form" question-id="{{ mcq.mcq.id }}">
                {% for choice in mcq.choices %}
                    <input type="checkbox" value="{{ choice.id }}">{{ choice.choice_text }}
                {% endfor %}
            </form>
        {% endfor %}
    </div>
    <br/>
    <button id="responseBtn" class="btn btn-default" type="submit">Submit</button>
    </div>
    <div class="container" id="thank-container">
        <h2>Thank You! for your submission</h2>
    </div>
<script>
    var csrf_token = "{{ csrf_token }}";
</script>
<script src="{% static 'main/js/jquery-3.1.1.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
<script src="{% static 'main/js/response.js' %}"></script>
</body>
</html>

main/templates/main/response_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <div class="container">
        <h3 class="page-header">{{ form.title }}</h3>
        {% for response in short_responses %}
            <div>
                <p>Question: {{ response.short_question.short_question_text }}</p>
                <p>Response: {{ response.short_response_text }}</p>
            </div><br>
        {% endfor %}
    </div>
</body>
</html>

main/templates/main/response_list.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Response</title>
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <div class="container">
        <h3>{{ form.title }}</h3>
        <h5 class="page-header">{{ form.description }}</h5>
        <h3 class="page-header">Questions</h3>
        {% for sq in sq_list %}
            <div>{{ sq.short_question_text }}</div>
        {% endfor %}
        <h3 class="page-header">Total Responses {{ count }}</h3>
        {% for response in responses %}
            <a href="{% url 'main:responseDetail' response.id %}">Response {{ response.id }}</a><br>
        {% endfor %}
    </div>
<script src="{% static 'main/js/jquery-3.1.1.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
<script src="{% static 'main/js/app.js' %}"></script>
</body>
</html>

main/templates/main/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>